### ISSUE TITLE
"Release matching query does not exist"

### ISSUE THREAD

**Issue by arza-zara** [weechat/weechat.org#63]
Running the site on debian unstable or archlinux gives
```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/weechat.org/weechat/news/views.py", line 57, in home
    return render_homepage(request, info_list, max_info, event_list, max_event)
  File "/weechat.org/weechat/news/views.py", line 37, in render_homepage
    'release_stable': Release.objects.get(version='stable'),
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Release matching query does not exist.
[21/Mar/2017 14:45:46] "GET / HTTP/1.1" 500 77885
```

No issue in debian jessie, and replacing `weechat.db` with the one from fresh install in debian jessie the site works normally.

**Comment by flashcode** [comment]
Thanks for reporting the problem.
Some things have changed in recent versions of Django, I have to update the install script.
